import java.io.*;
import java.util.*;
public class Anagrams{
  private static HashMap<String , ArrayList<String>>anagramMap = new HashMap<>();
  private static int totalWords = 0;
  private static int uniqueWords= 0;
  private static int anagramGroups =0;
  public static void main(String[]args) {
    Sysytem.out.println("====ANAGRAM FINDER FOR joyce1922_ulysses.txt ====");
    Sysytem.out.println("Starting at : " + new Date());
    Sysytem.out.println("-----------------------------------------")
      if (!processFile(" joyce1922_ulysses.txt")) {
            System.out.println("ERROR: Could not process file. Exiting.");
            return;
        }
    printStatistics();
        generateLatexFile("theAnagrams.tex");
        System.out.println("\nDone! Output written to theAnagrams.tex");
    }
  private static boolean processFile(String filename) {
        try {
            BufferedReader reader = new BufferedReader(new FileReader(filename));
            String line;
            int lineCount = 0;
           System.out.println("Reading file: " + filename);

            while ((line = reader.readLine()) != null) {
                lineCount++;
                processLine(line);
                if (lineCount % 1000 == 0) {
                    System.out.println("  Processed " + lineCount + " lines...");
                }
            }
            reader.close();
            System.out.println("File processing complete! " + lineCount + " lines read.");
            return true;

        } catch (FileNotFoundException e) {
            System.out.println("File not found: " + filename);
            System.out.println("Please ensure joyce1922_ulysses.txt is in the current directory.");
            return false;
        } catch (IOException e) {
            System.out.println("Error reading file: " + e.getMessage());
            return false;
        }
  }
    private static void processLine(String line){

        String[] words = line.split("\\s+");

        for (String word : words) {
            if (word.isEmpty()) continue;
            String cleanedWord = cleanWord(word);
            if (cleanedWord.isEmpty()) continue;
            processWord(cleanedWord);
        }
    }
    private static String cleanWord(String word) {
        String cleaned = word.replaceAll("^[^a-zA-Z0-9']+|[^a-zA-Z0-9']+$", "");
        cleaned = cleaned.toLowerCase();
        if (cleaned.length() < 2) return "";
        return cleaned;
    }
   private static void processWord(String word) {
        totalWords++;
      String signature = createSignature(word);
     if (!anagramMap.containsKey(signature)) {
        ArrayList<String> wordList = new ArrayList<>();
            wordList.add(word);
            anagramMap.put(signature, wordList);
            uniqueWords++;
  } else{
       ArrayList<String> wordList = anagramMap.get(signature);
            if (!wordList.contains(word)) {
                wordList.add(word);
            }
        }
    }
  private static String createSignature(String word) {
        char[] chars = word.toCharArray();
        Arrays.sort(chars);
        return new String(chars);
    }
   private static void printStatistics() {
        System.out.println("\n=== STATISTICS ===");
        System.out.println("Total words processed: " + totalWords);
        System.out.println("Unique words: " + uniqueWords);
        System.out.println("Unique signatures: " + anagramMap.size());
     anagramGroups = 0;
        int largestGroup = 0;
        String largestSignature = "";

        for (Map.Entry<String, ArrayList<String>> entry : anagramMap.entrySet()) {
            int size = entry.getValue().size();
            if (size > 1) {
                anagramGroups++;
                if (size > largestGroup) {
                    largestGroup = size;
                    largestSignature = entry.getKey();
                }
            }
        }
     System.out.println("Anagram groups found: " + anagramGroups);
        System.out.println("Largest anagram group: " + largestGroup + " words");
        if (largestGroup > 1) {
            System.out.println("  Signature: " + largestSignature);
            System.out.println("  Words: " + anagramMap.get(largestSignature));
        }
    }
  private static void generateLatexFile(String filename) {
        try {
            PrintWriter writer = new PrintWriter(new FileWriter(filename));
          writer.println("% LaTeX file generated by Anagrams.java");
            writer.println("% Contains all anagrams found in joyce1922_ulysses.txt");
            writer.println("\\documentclass{article}");
            writer.println("\\usepackage{geometry}");
            writer.println("\\geometry{a4paper, margin=1in}");
            writer.println("\\usepackage{multicol}");
            writer.println("\\usepackage{enumitem}");
            writer.println("\\title{Anagrams in James Joyce's Ulysses}");
            writer.println("\\author{Generated by 15practical}");
            writer.println("\\date{\\today}");
            writer.println("\\begin{document}");
            writer.println("\\maketitle");
            writer.println("\\begin{multicols}{3}");
            writer.println("\\begin{description}[itemsep=2pt, topsep=0pt]");
           ArrayList<String> signatures = new ArrayList<>(anagramMap.keySet());
            Collections.sort(signatures);

            int anagramCount = 0;
          for (String signature : signatures) {
                ArrayList<String> words = anagramMap.get(signature);
            if (words.size() > 1) {
                    anagramCount++;
               writer.print("  \\item[\\texttt{" + signature + "}] ");

                    for (int i = 0; i < words.size(); i++) {
                        writer.print(words.get(i));
                        if (i < words.size() - 1) {
                            writer.print(", ");
                        }
                    }
                    writer.println();
                }
          }
           writer.println("\\end{description}");
            writer.println("\\end{multicols}");
            writer.println("\\vfill");
            writer.println("\\begin{center}");
            writer.println("\\rule{0.5\\textwidth}{0.4pt}\\\\");
            writer.println("{\\small Total anagram groups: " + anagramCount + "}");
            writer.println("\\end{center}");
            writer.println("\\end{document}");

            writer.close();

            System.out.println("\nLaTeX file generated: " + filename);
            System.out.println("  Contains " + anagramCount + " anagram groups");

        } catch (IOException e) {
            System.out.println("Error writing LaTeX file: " + e.getMessage());
        }
    }
}
          
          
              
            
          

          
  
     
  
       
       
          


  
